#! /usr/bin/env python
"""Script for releasing a new version of ezconfig.

It keeps a .last_version_uploaded and if the version in VERSION is
different it will upload everything to to pipy and send the docs to readthedocs.
"""

from argparse import ArgumentParser
import logging

DEFAULT_LOG_FORMAT = "'%(asctime)s - %(name)s - %(levelname)s - %(message)s'"

def main():

    return

if __name__ == "_main__":

    arg_parser = ArgumentParser()
    arg_parser.add_argument("-v", action="store_const", dest="verbosity", const=logging.WARNING)
    arg_parser.add_argument("-vv", action="store_const", dest="verbosity", const=logging.INFO)
    arg_parser.add_argument("-vvv", action="store_const", dest="verbosity", const=logging.DEBUG)
    arg_parser.add_argument("-vvv", action="store_const", dest="verbosity", const=logging.DEBUG)
    arg_parser.add_argument("--log-format", action="store_const", const=DEFAULT_LOG_FORMAT)

    args = arg_parser.parse_args()
    logging.basicConfig(level=args.verbosity, format=args.log_format)

    main()
